package tp4_ejercicio3_musica;

public enum Resultados {
	CANCION_ESCUCHADA,
	USUARIO_INEXISTENTE,
	USUARIO_EXISTENTE,
	CANCION_INEXISTENTE,
	LIMITE_ALCANZADO,
	CANCION_NO_DISPONIBLE,
	CANCION_EXISTENTE;
	
}
